### ISSUE TITLE
AndroidX support?

### ISSUE THREAD

**Issue by zbrukas** [tschoffelen/react-native-email-link#25]
Hi. Will this project be receiving updates to support AndroidX?

**Comment by tschoffelen** [comment]
Since this library doesn't rely on any external dependencies, I think it will only need the `minVersion` and `targetVersion` of the Gradle config to be updated for AndroidX support, right?

Not too much of an Android dev myself, so any guidance with this is very much welcome! My company is using this library in a few different production apps, so I'm very much committed to keeping it up to date.

**Comment by tschoffelen** [comment]
Pretty sure this has been resolved by #34.
